require("basic")
require("plugins")
require("file-explorer")
require("mason-config")
require("lspsetup")
require("clangd")
require("gopls")
require("pyright")
require("luaLSP")
require("code-completion")
require("custom-keys")
require("debugging")
require("styling")
require("syntax-highlight")
require("autopairs")
print("hi! Welcome to zjj's neovim!")
